trigger:
- main

variables:
  ACR_NAME: <ACR name>
  IMAGE_NAME: <image name>
  RESOURCE_GROUP: <Azure RG name>
  AKS_NAME: <AKS name>
  SERVICE_CONNECTION_NAME: <service connection name>
  POOL_NAME: <agent pool name>

stages:
- stage: Build
  jobs:
  - job: Build
    pool: '$(POOL_NAME)'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'
      
    - task: Docker@2
      inputs:
        containerRegistry: '$(ACR_NAME)'
        repository: '$(IMAGE_NAME)'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: 'latest'
          
- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: Deploy
    pool: '$(POOL_NAME)'
    environment: 'aks-env'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Kubernetes@1
            inputs:
              connectionType: 'Azure Resource Manager'
              azureResourceGroup: '$(RESOURCE_GROUP)'
              kubernetesCluster: '$(AKS_NAME)'
              namespace: 'default'
              command: apply
              useConfigurationFile: true
              configuration: 'manifests/deployment.yml'
              secretType: 'dockerRegistry'
              containerRegistryType: 'Azure Container Registry'
              azureSubscriptionEndpoint: '$(SERVICE_CONNECTION_NAME)'
              azureContainerRegistry: '$(ACR_NAME)'
