apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-hello-world
  template:
    metadata:
      labels:
        app: flask-hello-world
    spec:
      containers:
      - name: flask-hello-world
        image: privatecontainerregistry.azurecr.io/flask-hello-world:$(Build.BuildId)
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flask-hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: flask-hello-world
